"""Seeding Alert Rules

Revision ID: 019ab566e5f7
Revises: 66bdcc9b5c7f
Create Date: 2023-12-19 08:58:40.290285

"""
import json
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sqlalchemy
from resources.alert_rules.alert_rule_model import AlertRule


# revision identifiers, used by Alembic.
revision: str = '019ab566e5f7'
down_revision: Union[str, None] = '66bdcc9b5c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with open(os.path.join(os.path.dirname(__file__), "../data/alert_rules_seed.json")) as f:
        alert_rules_data = f.read()
    op.bulk_insert(AlertRule.__table__,json.loads(alert_rules_data))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
